//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LessonManager.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        LessonManager.ServiceReference3.HelloWorldResponse HelloWorld(LessonManager.ServiceReference3.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.HelloWorldResponse> HelloWorldAsync(LessonManager.ServiceReference3.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetLessonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLesson", ReplyAction="*")]
        LessonManager.ServiceReference3.GetLessonResponse GetLesson(LessonManager.ServiceReference3.GetLessonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLesson", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.GetLessonResponse> GetLessonAsync(LessonManager.ServiceReference3.GetLessonRequest request);
        
        // CODEGEN: Generating message contract since element name GetLessonMgrDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLessonMgrDetails", ReplyAction="*")]
        LessonManager.ServiceReference3.GetLessonMgrDetailsResponse GetLessonMgrDetails(LessonManager.ServiceReference3.GetLessonMgrDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLessonMgrDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.GetLessonMgrDetailsResponse> GetLessonMgrDetailsAsync(LessonManager.ServiceReference3.GetLessonMgrDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name xmlNote from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadNotes", ReplyAction="*")]
        LessonManager.ServiceReference3.UploadNotesResponse UploadNotes(LessonManager.ServiceReference3.UploadNotesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadNotes", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.UploadNotesResponse> UploadNotesAsync(LessonManager.ServiceReference3.UploadNotesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LessonManager.ServiceReference3.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LessonManager.ServiceReference3.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLessonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLesson", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.GetLessonRequestBody Body;
        
        public GetLessonRequest() {
        }
        
        public GetLessonRequest(LessonManager.ServiceReference3.GetLessonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLessonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Instructor_ID;
        
        public GetLessonRequestBody() {
        }
        
        public GetLessonRequestBody(int Instructor_ID) {
            this.Instructor_ID = Instructor_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLessonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLessonResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.GetLessonResponseBody Body;
        
        public GetLessonResponse() {
        }
        
        public GetLessonResponse(LessonManager.ServiceReference3.GetLessonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLessonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLessonResult;
        
        public GetLessonResponseBody() {
        }
        
        public GetLessonResponseBody(string GetLessonResult) {
            this.GetLessonResult = GetLessonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLessonMgrDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLessonMgrDetails", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.GetLessonMgrDetailsRequestBody Body;
        
        public GetLessonMgrDetailsRequest() {
        }
        
        public GetLessonMgrDetailsRequest(LessonManager.ServiceReference3.GetLessonMgrDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLessonMgrDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Booking_ID;
        
        public GetLessonMgrDetailsRequestBody() {
        }
        
        public GetLessonMgrDetailsRequestBody(int Booking_ID) {
            this.Booking_ID = Booking_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLessonMgrDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLessonMgrDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.GetLessonMgrDetailsResponseBody Body;
        
        public GetLessonMgrDetailsResponse() {
        }
        
        public GetLessonMgrDetailsResponse(LessonManager.ServiceReference3.GetLessonMgrDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLessonMgrDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLessonMgrDetailsResult;
        
        public GetLessonMgrDetailsResponseBody() {
        }
        
        public GetLessonMgrDetailsResponseBody(string GetLessonMgrDetailsResult) {
            this.GetLessonMgrDetailsResult = GetLessonMgrDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadNotesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadNotes", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.UploadNotesRequestBody Body;
        
        public UploadNotesRequest() {
        }
        
        public UploadNotesRequest(LessonManager.ServiceReference3.UploadNotesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadNotesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlNote;
        
        public UploadNotesRequestBody() {
        }
        
        public UploadNotesRequestBody(string xmlNote) {
            this.xmlNote = xmlNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadNotesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadNotesResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference3.UploadNotesResponseBody Body;
        
        public UploadNotesResponse() {
        }
        
        public UploadNotesResponse(LessonManager.ServiceReference3.UploadNotesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadNotesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadNotesResult;
        
        public UploadNotesResponseBody() {
        }
        
        public UploadNotesResponseBody(string UploadNotesResult) {
            this.UploadNotesResult = UploadNotesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : LessonManager.ServiceReference3.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<LessonManager.ServiceReference3.WebService1Soap>, LessonManager.ServiceReference3.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference3.HelloWorldResponse LessonManager.ServiceReference3.WebService1Soap.HelloWorld(LessonManager.ServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LessonManager.ServiceReference3.HelloWorldRequest inValue = new LessonManager.ServiceReference3.HelloWorldRequest();
            inValue.Body = new LessonManager.ServiceReference3.HelloWorldRequestBody();
            LessonManager.ServiceReference3.HelloWorldResponse retVal = ((LessonManager.ServiceReference3.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.HelloWorldResponse> LessonManager.ServiceReference3.WebService1Soap.HelloWorldAsync(LessonManager.ServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference3.HelloWorldResponse> HelloWorldAsync() {
            LessonManager.ServiceReference3.HelloWorldRequest inValue = new LessonManager.ServiceReference3.HelloWorldRequest();
            inValue.Body = new LessonManager.ServiceReference3.HelloWorldRequestBody();
            return ((LessonManager.ServiceReference3.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference3.GetLessonResponse LessonManager.ServiceReference3.WebService1Soap.GetLesson(LessonManager.ServiceReference3.GetLessonRequest request) {
            return base.Channel.GetLesson(request);
        }
        
        public string GetLesson(int Instructor_ID) {
            LessonManager.ServiceReference3.GetLessonRequest inValue = new LessonManager.ServiceReference3.GetLessonRequest();
            inValue.Body = new LessonManager.ServiceReference3.GetLessonRequestBody();
            inValue.Body.Instructor_ID = Instructor_ID;
            LessonManager.ServiceReference3.GetLessonResponse retVal = ((LessonManager.ServiceReference3.WebService1Soap)(this)).GetLesson(inValue);
            return retVal.Body.GetLessonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.GetLessonResponse> LessonManager.ServiceReference3.WebService1Soap.GetLessonAsync(LessonManager.ServiceReference3.GetLessonRequest request) {
            return base.Channel.GetLessonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference3.GetLessonResponse> GetLessonAsync(int Instructor_ID) {
            LessonManager.ServiceReference3.GetLessonRequest inValue = new LessonManager.ServiceReference3.GetLessonRequest();
            inValue.Body = new LessonManager.ServiceReference3.GetLessonRequestBody();
            inValue.Body.Instructor_ID = Instructor_ID;
            return ((LessonManager.ServiceReference3.WebService1Soap)(this)).GetLessonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference3.GetLessonMgrDetailsResponse LessonManager.ServiceReference3.WebService1Soap.GetLessonMgrDetails(LessonManager.ServiceReference3.GetLessonMgrDetailsRequest request) {
            return base.Channel.GetLessonMgrDetails(request);
        }
        
        public string GetLessonMgrDetails(int Booking_ID) {
            LessonManager.ServiceReference3.GetLessonMgrDetailsRequest inValue = new LessonManager.ServiceReference3.GetLessonMgrDetailsRequest();
            inValue.Body = new LessonManager.ServiceReference3.GetLessonMgrDetailsRequestBody();
            inValue.Body.Booking_ID = Booking_ID;
            LessonManager.ServiceReference3.GetLessonMgrDetailsResponse retVal = ((LessonManager.ServiceReference3.WebService1Soap)(this)).GetLessonMgrDetails(inValue);
            return retVal.Body.GetLessonMgrDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.GetLessonMgrDetailsResponse> LessonManager.ServiceReference3.WebService1Soap.GetLessonMgrDetailsAsync(LessonManager.ServiceReference3.GetLessonMgrDetailsRequest request) {
            return base.Channel.GetLessonMgrDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference3.GetLessonMgrDetailsResponse> GetLessonMgrDetailsAsync(int Booking_ID) {
            LessonManager.ServiceReference3.GetLessonMgrDetailsRequest inValue = new LessonManager.ServiceReference3.GetLessonMgrDetailsRequest();
            inValue.Body = new LessonManager.ServiceReference3.GetLessonMgrDetailsRequestBody();
            inValue.Body.Booking_ID = Booking_ID;
            return ((LessonManager.ServiceReference3.WebService1Soap)(this)).GetLessonMgrDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference3.UploadNotesResponse LessonManager.ServiceReference3.WebService1Soap.UploadNotes(LessonManager.ServiceReference3.UploadNotesRequest request) {
            return base.Channel.UploadNotes(request);
        }
        
        public string UploadNotes(string xmlNote) {
            LessonManager.ServiceReference3.UploadNotesRequest inValue = new LessonManager.ServiceReference3.UploadNotesRequest();
            inValue.Body = new LessonManager.ServiceReference3.UploadNotesRequestBody();
            inValue.Body.xmlNote = xmlNote;
            LessonManager.ServiceReference3.UploadNotesResponse retVal = ((LessonManager.ServiceReference3.WebService1Soap)(this)).UploadNotes(inValue);
            return retVal.Body.UploadNotesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference3.UploadNotesResponse> LessonManager.ServiceReference3.WebService1Soap.UploadNotesAsync(LessonManager.ServiceReference3.UploadNotesRequest request) {
            return base.Channel.UploadNotesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference3.UploadNotesResponse> UploadNotesAsync(string xmlNote) {
            LessonManager.ServiceReference3.UploadNotesRequest inValue = new LessonManager.ServiceReference3.UploadNotesRequest();
            inValue.Body = new LessonManager.ServiceReference3.UploadNotesRequestBody();
            inValue.Body.xmlNote = xmlNote;
            return ((LessonManager.ServiceReference3.WebService1Soap)(this)).UploadNotesAsync(inValue);
        }
    }
}
