//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LessonManager.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        LessonManager.ServiceReference1.HelloWorldResponse HelloWorld(LessonManager.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference1.HelloWorldResponse> HelloWorldAsync(LessonManager.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetLessonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLesson", ReplyAction="*")]
        LessonManager.ServiceReference1.GetLessonResponse GetLesson(LessonManager.ServiceReference1.GetLessonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLesson", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference1.GetLessonResponse> GetLessonAsync(LessonManager.ServiceReference1.GetLessonRequest request);
        
        // CODEGEN: Generating message contract since element name Start_Time from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadNotes", ReplyAction="*")]
        LessonManager.ServiceReference1.UploadNotesResponse UploadNotes(LessonManager.ServiceReference1.UploadNotesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadNotes", ReplyAction="*")]
        System.Threading.Tasks.Task<LessonManager.ServiceReference1.UploadNotesResponse> UploadNotesAsync(LessonManager.ServiceReference1.UploadNotesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LessonManager.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LessonManager.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLessonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLesson", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference1.GetLessonRequestBody Body;
        
        public GetLessonRequest() {
        }
        
        public GetLessonRequest(LessonManager.ServiceReference1.GetLessonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLessonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CustomerID;
        
        public GetLessonRequestBody() {
        }
        
        public GetLessonRequestBody(int CustomerID) {
            this.CustomerID = CustomerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLessonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLessonResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference1.GetLessonResponseBody Body;
        
        public GetLessonResponse() {
        }
        
        public GetLessonResponse(LessonManager.ServiceReference1.GetLessonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLessonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLessonResult;
        
        public GetLessonResponseBody() {
        }
        
        public GetLessonResponseBody(string GetLessonResult) {
            this.GetLessonResult = GetLessonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadNotesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadNotes", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference1.UploadNotesRequestBody Body;
        
        public UploadNotesRequest() {
        }
        
        public UploadNotesRequest(LessonManager.ServiceReference1.UploadNotesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadNotesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Start_Time;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string note;
        
        public UploadNotesRequestBody() {
        }
        
        public UploadNotesRequestBody(string Start_Time, decimal duration, string note) {
            this.Start_Time = Start_Time;
            this.duration = duration;
            this.note = note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadNotesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadNotesResponse", Namespace="http://tempuri.org/", Order=0)]
        public LessonManager.ServiceReference1.UploadNotesResponseBody Body;
        
        public UploadNotesResponse() {
        }
        
        public UploadNotesResponse(LessonManager.ServiceReference1.UploadNotesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadNotesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadNotesResult;
        
        public UploadNotesResponseBody() {
        }
        
        public UploadNotesResponseBody(string UploadNotesResult) {
            this.UploadNotesResult = UploadNotesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : LessonManager.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<LessonManager.ServiceReference1.WebService1Soap>, LessonManager.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference1.HelloWorldResponse LessonManager.ServiceReference1.WebService1Soap.HelloWorld(LessonManager.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LessonManager.ServiceReference1.HelloWorldRequest inValue = new LessonManager.ServiceReference1.HelloWorldRequest();
            inValue.Body = new LessonManager.ServiceReference1.HelloWorldRequestBody();
            LessonManager.ServiceReference1.HelloWorldResponse retVal = ((LessonManager.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference1.HelloWorldResponse> LessonManager.ServiceReference1.WebService1Soap.HelloWorldAsync(LessonManager.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            LessonManager.ServiceReference1.HelloWorldRequest inValue = new LessonManager.ServiceReference1.HelloWorldRequest();
            inValue.Body = new LessonManager.ServiceReference1.HelloWorldRequestBody();
            return ((LessonManager.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference1.GetLessonResponse LessonManager.ServiceReference1.WebService1Soap.GetLesson(LessonManager.ServiceReference1.GetLessonRequest request) {
            return base.Channel.GetLesson(request);
        }
        
        public string GetLesson(int CustomerID) {
            LessonManager.ServiceReference1.GetLessonRequest inValue = new LessonManager.ServiceReference1.GetLessonRequest();
            inValue.Body = new LessonManager.ServiceReference1.GetLessonRequestBody();
            inValue.Body.CustomerID = CustomerID;
            LessonManager.ServiceReference1.GetLessonResponse retVal = ((LessonManager.ServiceReference1.WebService1Soap)(this)).GetLesson(inValue);
            return retVal.Body.GetLessonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference1.GetLessonResponse> LessonManager.ServiceReference1.WebService1Soap.GetLessonAsync(LessonManager.ServiceReference1.GetLessonRequest request) {
            return base.Channel.GetLessonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference1.GetLessonResponse> GetLessonAsync(int CustomerID) {
            LessonManager.ServiceReference1.GetLessonRequest inValue = new LessonManager.ServiceReference1.GetLessonRequest();
            inValue.Body = new LessonManager.ServiceReference1.GetLessonRequestBody();
            inValue.Body.CustomerID = CustomerID;
            return ((LessonManager.ServiceReference1.WebService1Soap)(this)).GetLessonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LessonManager.ServiceReference1.UploadNotesResponse LessonManager.ServiceReference1.WebService1Soap.UploadNotes(LessonManager.ServiceReference1.UploadNotesRequest request) {
            return base.Channel.UploadNotes(request);
        }
        
        public string UploadNotes(string Start_Time, decimal duration, string note) {
            LessonManager.ServiceReference1.UploadNotesRequest inValue = new LessonManager.ServiceReference1.UploadNotesRequest();
            inValue.Body = new LessonManager.ServiceReference1.UploadNotesRequestBody();
            inValue.Body.Start_Time = Start_Time;
            inValue.Body.duration = duration;
            inValue.Body.note = note;
            LessonManager.ServiceReference1.UploadNotesResponse retVal = ((LessonManager.ServiceReference1.WebService1Soap)(this)).UploadNotes(inValue);
            return retVal.Body.UploadNotesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LessonManager.ServiceReference1.UploadNotesResponse> LessonManager.ServiceReference1.WebService1Soap.UploadNotesAsync(LessonManager.ServiceReference1.UploadNotesRequest request) {
            return base.Channel.UploadNotesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LessonManager.ServiceReference1.UploadNotesResponse> UploadNotesAsync(string Start_Time, decimal duration, string note) {
            LessonManager.ServiceReference1.UploadNotesRequest inValue = new LessonManager.ServiceReference1.UploadNotesRequest();
            inValue.Body = new LessonManager.ServiceReference1.UploadNotesRequestBody();
            inValue.Body.Start_Time = Start_Time;
            inValue.Body.duration = duration;
            inValue.Body.note = note;
            return ((LessonManager.ServiceReference1.WebService1Soap)(this)).UploadNotesAsync(inValue);
        }
    }
}
